- hosts: localhost
  tasks:
    - name: Install dependencies
      package:
        name:
          - dnf-plugins-core
        state: latest
      become: yes
    
    - name: Gpg download
      shell: sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
      become: yes

    - name: Rpm import
      shell: sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      become: yes

    - name: Install Brave browser
      package: 
        name:
          - brave-browser
        state: latest
      become: yes
