- hosts: localhost
  tasks:
    - name: Install dependencies
      package:
        name:
          - alacritty
          - git
          - zsh
          - starship
          - tmux
          - picom
          - i3
          - polybar
          - stow
          - pcmanfm
          - feh
          - rofi
          - fzf
        state: latest
      become: yes

    - name: Delete existing .dotfiles
      file:
        state: absent
        path: $HOME/.dotfiles

    - name: Clone my .dotfiles
      ansible.builtin.git:
        repo: 'https://github.com/Try3D/.dotfiles.git'
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles"

    - name: Clear existing .dotfiles
      shell: "stow -D */"

    - name: Install .dotfiles
      shell: "stow */"

    - name: Delete existing .zsh-plugins
      file:
        state: absent
        path: $HOME/.zsh-plugins/
  
    - name: Create new .zsh-plugins folder
      file:
        state: present
        path: $HOME/.zsh-plugins/

    - name: Clone my .dotfiles
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
        dest: "{{ lookup('env', 'HOME') }}/.zsh-plugins/zsh-autosuggestions"

        repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
        dest: "{{ lookup('env', 'HOME') }}/.zsh-plugins/zsh-syntax-highlighting"
